Repository Seo3Kyung/S3K_BE, pull requests merged in 2025-06, with the labels that each got.

#9 인증 인가 작업
  build.gradle
  docker-compose.yml
  src/main/java/com/s3k/backend/BackendApplication.java
  src/main/java/com/s3k/backend/global/DatabaseConfig.java
  src/main/java/com/s3k/backend/global/EncodedIdDeserializer.java
  src/main/java/com/s3k/backend/global/EncodedIdSerializer.java
  src/main/java/com/s3k/backend/global/EncryptUtil.java
  src/main/java/com/s3k/backend/global/SecurityConfig.java
  src/main/java/com/s3k/backend/member/Member.java
  src/main/java/com/s3k/backend/member/controller/MemberController.java
  src/main/java/com/s3k/backend/member/dto/MemberDefaultDto.java
  src/main/java/com/s3k/backend/member/dto/MemberSigninDto.java
  src/main/java/com/s3k/backend/member/dto/MemberSignupDto.java
  src/main/java/com/s3k/backend/member/dto/feign/KakaoTokenDto.java
  src/main/java/com/s3k/backend/member/entity/Member.java
  src/main/java/com/s3k/backend/member/enums/Role.java
  src/main/java/com/s3k/backend/member/enums/Sns.java
  src/main/java/com/s3k/backend/member/enums/Status.java
  src/main/java/com/s3k/backend/member/mapper/MemberMapper.java
  src/main/java/com/s3k/backend/member/service/MemberService.java
  src/main/java/com/s3k/backend/member/service/inner/KakaoFeign.java
  src/main/java/com/s3k/backend/member/service/inner/KakaoProvider.java
  src/main/java/com/s3k/backend/member/service/inner/MemberConverter.java
  src/main/java/com/s3k/backend/security/config/SecurityConfig.java
  src/main/java/com/s3k/backend/security/config/SecurityConstants.java
  src/main/java/com/s3k/backend/security/filter/CustomJwtAuthenticationFilter.java
  src/main/java/com/s3k/backend/security/handler/CustomAccessDeniedHandler.java
  src/main/java/com/s3k/backend/security/handler/CustomAuthenticationEntryPoint.java
  src/main/java/com/s3k/backend/security/handler/OAuth2LoginFailureHandler.java
  src/main/java/com/s3k/backend/security/handler/OAuth2LoginSuccessHandler.java
  src/main/java/com/s3k/backend/security/jwt/JwtTokenIssuer.java
  src/main/java/com/s3k/backend/security/jwt/JwtTokenValidator.java
  src/main/java/com/s3k/backend/security/service/CustomOidcUserService.java
  src/main/java/com/s3k/backend/security/util/RedirectUrlUtils.java
  src/main/resources/application.yml
  src/main/resources/mapper/MEMBER_MAPPER.xml
  src/test/java/com/s3k/backend/mapper/MemberMapperTests.java
  src/test/java/com/s3k/backend/security/RedirectUrlTest.java
Labels: enhancement

#10 [feature/001] openFeign 관련 로직 주석처리
  src/main/java/com/s3k/backend/member/controller/MemberController.java
  src/main/java/com/s3k/backend/member/service/MemberService.java
  src/main/java/com/s3k/backend/member/service/inner/KakaoFeign.java
  src/main/java/com/s3k/backend/member/service/inner/KakaoProvider.java
  src/main/java/com/s3k/backend/member/service/inner/MemberConverter.java
  src/test/java/com/s3k/backend/BackendApplicationTests.java
  src/test/java/com/s3k/backend/mapper/MemberMapperTests.java
  src/test/java/com/s3k/backend/security/RedirectUrlTest.java
Labels: enhancement

#11 [feature/006] 응답 공통화
  src/main/java/com/s3k/backend/global/BasicController.java
  src/main/java/com/s3k/backend/global/dto/ApisResponse.java
  src/main/java/com/s3k/backend/global/enums/ApiResponseStatus.java
Labels: bug, enhancement

#17 [docs-007] application-dev OAuth redirect 경로 추가
  src/main/resources/application-dev.yml
Labels: bug
